// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FinanceTracker.DAL;

public partial class Account
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public int TypeId { get; set; }

    public decimal Balance { get; set; }

    public int UserId { get; set; }

    public virtual ICollection<Transaction> Transaction { get; set; } = new List<Transaction>();

    public virtual TypeAccount Type { get; set; } = null!;

    public virtual User User { get; set; } = null!;
}