// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FinanceTracker.DAL;

public partial class CategoryTransaction
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public int Order { get; set; }

    public bool IsIncome { get; set; }

    public virtual ICollection<Transaction> Transaction { get; set; } = new List<Transaction>();
}