// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FinanceTracker.DAL;

public partial class Transaction
{
    public int Id { get; set; }

    public decimal Amount { get; set; }

    public DateTime Date { get; set; }

    public int CategoryId { get; set; }

    public string Description { get; set; } = null!;

    public int AccountId { get; set; }

    public int UserId { get; set; }

    public virtual Account Account { get; set; } = null!;

    public virtual CategoryTransaction Category { get; set; } = null!;

    public virtual User User { get; set; } = null!;
}