// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FinanceTracker.DAL;

public partial class User
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string Password { get; set; } = null!;

    public virtual ICollection<Account> Account { get; set; } = new List<Account>();

    public virtual ICollection<Transaction> Transaction { get; set; } = new List<Transaction>();
}